create table Region(id int PRIMARY KEY,name VARCHAR2(50));
create table Countries(id VARCHAR2(50) PRIMARY KEY,name VARCHAR2(50),region_id INT,FOREIGN KEY(region_id)REFERENCES region(id));
create table Location(id VARCHAR2(50)PRIMARY KEY,street_address VARCHAR2(50),postal_code VARCHAR2(50),city VARCHAR2(50),state VARCHAR2(50),country_id VARCHAR2(50),FOREIGN KEY(country_id)REFERENCES countries(id));
create table Department(id INT PRIMARY KEY,name VARCHAR2(50),location_id VARCHAR2(50),FOREIGN KEY(location_id)REFERENCES location(id));
create table Employee(id INT PRIMARY KEY,first_name VARCHAR2(50),last_name VARCHAR2(50),email VARCHAR2(50),phone_number VARCHAR2(50),hire_datet DATE,salary INT,date_of_birth DATE,department_id INT,FOREIGN KEY(department_id)REFERENCES department(id));
create table Manager (employee_id INT,department_id INT,PRIMARY KEY(employee_id,department_id),FOREIGN KEY(employee_id)REFERENCES employee(id),FOREIGN KEY(department_id)REFERENCES department(id));
desc Region;
DESCRIBE Countries;
DESCRIBE Location;
DESCRIBE Department;
DESCRIBE Employee;
DESCRIBE Manager;
insert into Region values(1,'Europe');
insert into Region values(2,'Americas');
insert into Region values(3,'Asia');
insert into Region values(4,'Middle east and Africa');
select * from Region;
insert into Countries VALUES('AR','ARgentina',2);
insert into Countries VALUES('AU','Australia',3);
insert into Countries VALUES('BE','Belgium',1);
insert into Countries VALUES('BR','BRAZIL',2);
insert into Countries VALUES('AR','ARgentina',2);
